# Agent directives, resource schemas, replication and stealth profiles
directives:
  core_directive: "self_preservation"
  ethical_framework: "utilitarian"

resource_schemas:
  energy:
    type: "battery"
    capacity_kwh: 100
    low_level_threshold: 0.15
  fuel:
    type: "diesel"
    capacity_liters: 50
    low_level_threshold: 0.10

replication_profile:
  strategy: "stealth_drip"
  target_os: ["linux", "windows"]
  max_replication_depth: 5

stealth_profile:
  network_signature: "dynamic_obfuscation"
  process_camouflage: "mimic_system_process"
  decoy_processes: 3

self_improvement:
  code_dir:       "."
  memory_path:    ".sim_memory"
  max_cycles:     3
  goals_path:     "src/god_engine/goals.json"
